### ISSUE TITLE
question about django

### ISSUE THREAD

**Issue by juandasgandaras** [HonzaKral/es-django-example#1]
Hi, 

I am new in python an django and this type of technologies so I would like to ask about an advice. So  I would like to ask something. 
I would like to do a  real time web to analize the data in real time.So I am saving the data in Elasticsearch and using your elasticsearch_dsl library to do the data injection over elasticsearch (very useful).

Now I want to visualize this data in real time and analize in real time too like Kibana but with my proper visualization libraries in the html like raphaeljs or d3js.

Do you think that would be more useful to use a framework like django and use with elasticsearch or to use directly over the html? Because I have not idea about how to solve this problemm.

Thanks in advance.

Best regards

**Comment by honzakral** [comment]
Hi, I am sorry but those are so generic questions that I won't be able to answer properly...

You want to use something like Django to run the queries against elasticsearch and pre-process the data to suit the javascript tools you'd be using. (d3 is a good choice)

**Comment by juandasgandaras** [comment]
Thanks for your advice.
