### ISSUE TITLE
Change the view to use a django Form instead of processing data manually

### ISSUE THREAD

**Issue by honzakral** [HonzaKral/es-django-example#12]
Data processing in view:
https://github.com/HonzaKral/es-django-example/blob/master/qa/views.py#L21-L25

**Comment by aavrug** [comment]
Just sent a PR please have a look https://github.com/HonzaKral/es-django-example/pull/14

**Comment by honzakral** [comment]
Closed via #14, thanks @aavrug!

**Comment by aavrug** [comment]
Thanks for accepting the PR.
