### ISSUE TITLE
Attachment Field

### ISSUE THREAD

**Issue by TheCthulhuKid** [HonzaKral/es-django-example#16]
Hi,

Is there any possibility of you adding an example of using the `Attachment` field? Or, in the case that I somehow missed (definitely a possibility...), point me to where I can find something in the docs?

Cheers!

**Comment by TheCthulhuKid** [comment]
Or should I just stick to using `elasticsearch.py` directly for anything with an attachment?

**Comment by karmi** [comment]
@gileadslostson, with the Stackoverflow dataset, there's not really a natural example for handling attachments... so yes, just using the Python client for handling attachments (via the Ingest plugin?) should be straightforward..

**Comment by TheCthulhuKid** [comment]
@karmi cheers! It is fairly straightforward =) I was just hoping for a way to use it in DSL. Thanks anyway.
