### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by dco5** [HonzaKral/es-django-example#4]
Hello,

Can you please tell me if with this code you are indexing every time the app qa starts:

from django.apps import AppConfig
from django.conf import settings

from elasticsearch_dsl.connections import connections
from elasticsearch.exceptions import NotFoundError

from .search import Question, Answer

class QAConfig(AppConfig):
    name = 'qa'
    verbose_name = "Q & A"

```
def ready(self):
    connections.configure(**settings.ES_CONNECTIONS)
    try:
        # FIXME: this shouldn't be run before index_data!
        Question._doc_type.refresh()
        Answer._doc_type.refresh()
    except NotFoundError:
        pass
```

Does .refresh() updates the index?

I am trying to figure out there to create the connection for elasticsearch so that it can be use all over the apps. 

I am currently doing it in the settings.py:
from elasticsearch_dsl.connections import connections
....
# Elastic Search

connections.create_connection(hosts=['localhost:9200'])

But I have a feeling that is really bad and I should do that somewhere else. I was thinking on doing it in the apps.py so that is why I was looking at your qa apps.py.

Thanks!

**Comment by honzakral** [comment]
Hi,

`refresh` doesn't update the index - it downloads the mappings definitions from elasticsearch and updated the `DocType` objects with fields that exist in the mapping but not on the class itself (fields that were created automatically by elasticsearch via dynamic mapping process).

To create a connection that is available everywhere just call the `connections.configure` or `create_connection`. The best place for that is indeed the `ready` method which will be called by django on initialization.

Hope this helps.

**Comment by dco5** [comment]
Thank you so much! This helps A LOT!
