### ISSUE TITLE
dropbox url not work

### ISSUE THREAD

**Issue by rmrf** [HonzaKral/es-django-example#5]
https://www.dropbox.com/s/eeocipgw6y6pk89/coffee.zip?dl=0

> The file you’re looking for has been moved or deleted.
> Please see this article for details on why a shared link might stop working.

**Comment by honzakral** [comment]
I am sorry, it's probably a stale link. You can get the original file here: https://archive.org/details/stackexchange (direct link - https://archive.org/download/stackexchange/coffee.stackexchange.com.7z)

or extract it from the `tutorial.zip` that is present here in releases: https://github.com/HonzaKral/es-django-example/releases

I will leave this issue open to remind me to fix the link, thanks for the report!

**Comment by rmrf** [comment]
Thank you, I got the 7z file now.

**Comment by karmi** [comment]
@HonzaKral, note that you can upload the file to a "Releases" section if this repository, so it's less probably the link will get stale? I did it recently with https://github.com/elastic/elasticsearch-rails/releases/tag/dischord.yml

**Comment by honzakral** [comment]
Thanks @karmi, I think the proper solution here is to expand the docs to point to the actual page with the `7z` files (0) and provide detailed instructions on how to import the data.

0 - https://archive.org/download/stackexchange/
