### ISSUE TITLE
q search failed (seems highlight related)

### ISSUE THREAD

**Issue by rmrf** [HonzaKral/es-django-example#7]
runserver can successfully start the web site, tags search and months search works fine. 
but q search failed. 
here is the error mesg:

`TransportError: TransportError(500, u'search_phase_execution_exception', u"can't load global ordinals for reader of type: class org.apache.lucene.search.highlight.WeightedSpanTermExtractor$DelegatingLeafReader must be a DirectoryReader")`

I have tried ES v2.3.0, v2.1.1, same error. 
Django Version: 1.9.5

I did some Google search, seems highlight related.

**Comment by lightstrike** [comment]
I hit this error as well, it is highlight related. Specifically, it seems related to https://github.com/elastic/elasticsearch/pull/19616

**Comment by honzakral** [comment]
Oh yes, I am sorry. There is currently a bug that affects the example. to fix just override the `highlight` method to just return the search argument. I will push the temporary fix soon.

I am sorry @rmrf, I somehow missed this issue, my apologies!

**Comment by honzakral** [comment]
pushed a "fix" in 95c9841adffef7d00de4286e738e15236c4de6b8
